# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    working_directory: ~/tdd-workshop
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
          name: 'yarn install'
          command: 'yarn install'
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: 'Linting'
          command: 'yarn lint'
      - run:
          name: 'Run tests'
          command: 'yarn test:ci'
